### ISSUE TITLE
Pokkit is being disabled automatically

### ISSUE THREAD

**Issue by Bluefrosting** [PetteriM1/Pokkit#27]
Whenever I start the server, pokkit is automatically disabled for some reason. I'm not entirely sure what to do.

08.03 07:08:32 [Server] ERROR [Pokkit] Error disabling plugin
08.03 07:08:32 [Server] INFO java.lang.reflect.InvocationTargetException: null
08.03 07:08:32 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
08.03 07:08:32 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
08.03 07:08:32 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
08.03 07:08:32 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
08.03 07:08:32 [Server] INFO at nl.rutgerkok.pokkit.startup.NukkitHook.onEnable(NukkitHook.java:26) [Pokkit-0.9.6.jar:0.9.6]
08.03 07:08:32 [Server] INFO at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) [nukkit.jar:?]
08.03 07:08:32 [Server] INFO at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) [nukkit.jar:?]
08.03 07:08:32 [Server] INFO at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:436) [nukkit.jar:?]
08.03 07:08:32 [Server] INFO at cn.nukkit.Server.enablePlugin(Server.java:748) [nukkit.jar:?]
08.03 07:08:32 [Server] INFO at cn.nukkit.Server.enablePlugins(Server.java:737) [nukkit.jar:?]
08.03 07:08:32 [Server] INFO at cn.nukkit.Server.<init>(Server.java:580) [nukkit.jar:?]
08.03 07:08:32 [Server] INFO at cn.nukkit.Nukkit.main(Nukkit.java:120) [nukkit.jar:?]
08.03 07:08:32 [Server] INFO Caused by: java.lang.NullPointerException
08.03 07:08:32 [Server] INFO at nl.rutgerkok.pokkit.pluginservice.PluginService.enablePlugins(PluginService.java:19) ~[?:?]
08.03 07:08:32 [Server] INFO at nl.rutgerkok.pokkit.pluginservice.PluginService.onEnable(PluginService.java:29) ~[?:?]
08.03 07:08:32 [Server] INFO at nl.rutgerkok.pokkit.Pokkit.lambda$onEnable$1(Pokkit.java:101) ~[?:?]
08.03 07:08:32 [Server] INFO at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408) ~[nukkit.jar:?]
08.03 07:08:32 [Server] INFO at nl.rutgerkok.pokkit.Pokkit.onEnable(Pokkit.java:101) ~[?:?]

**Comment by WINGS07** [comment]
Same issue

**Comment by Bluefrosting** [comment]
> Same issue

I used PowerNukkit jar instead of NukkitX and it worked!
