### ISSUE TITLE
Pokkit For PocketMine

### ISSUE THREAD

**Issue by BugPatcher** [PetteriM1/Pokkit#31]
I know this isn't exactly an issue, but I'd really like this to be implemented. Nukkit does not support blocks from the aquatic update, and this really impacts the survival gameplay. What I am asking is for a simple plugin that translates plugins from Java to a plugin in
PocketMine. I know this is complicated, but really I just want to convert a simple plugin such as DiscordSRV. Thank you for considering my application.

**Comment by SunshroomChan** [comment]
Pocketmine using PHP +and C++ and API is more change so translating it is really hard and cause many bugs or error
